name: Publish image to Github Hub and deploy to Azure
on:
  [push]

env:
  AZURE_WEBAPP_NAME: anvil-home
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker login ghcr.io -u psubiantogmail -p ${{ secrets.DOCKER_PAT }}
          docker build --file ./Dockerfile -t ghcr.io/psubiantogmail/home-ghcr:latest .
      - name: publish
        run: |
          docker push ghcr.io/psubiantogmail/home-ghcr:latest
      - name: pushtoazure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH}}
